variant: fcos
version: 1.5.0

passwd:
  users:
    - name: core
      password_hash: "$6$f1891cea80fc05e433c943254c6bdabc159577a02a7395dfebbfbc4f7661d4af56f2d372131a45936de40160007368a56ef216a30cb202c66d3145fd24380906"

storage:
  files:
    - path: /etc/motd
      mode: 0644
      contents:
        inline: |
          ============================
          appliance-bootstrap
          step1 ignition OK
          ============================

systemd:
  units:
    - name: sshd.service
      enabled: true
